#!/bin/sh

read -p "NVIDIA? (y or n) " nvidia
if [[ $nvidia == "y" ]] || [[ $nvidia == "Y" ]]; then
    sudo pacman -S nvidia-open-dkms libva
    #cat "nvidia_drm.modeset=1" >> /boot/loader/entries/arch.conf
    #cat "nvidia nvidia_modeset nvidia_uvm nvidia_drm" >> /etc/mkinitcpio.conf
    #cat "options nvidia-drm modeset=1" >> /etc/modprobe.d/nvidia.conf
fi

if [[ -z "sudo pacman -Q | grep paru" ]]; then
    sudo pacman -S --needed base-devel
    cd /tmp
    git clone https://aur.archlinux.org/paru.git
    cd paru
    makepkg -si
    cd
fi

sudo pacman -S \
    pipewire wireplumber polkit-gnome qt5-wayland qt6-wayland xdg-desktop-portal-hyprland \
    waybar dunst \
    foot fastfetch starship \
    hyprland hyprpaper \
    ly \
    mpd ncmpcpp mpc \
    neovim nodejs npm \
    yazi ffmpegthumbnailer ntfs-3g \
    bat bemenu btop \
    blender gimp inkscape godot \
    grim slurp \
    hugo rust typst \
    imv mpv \
    man-db \
    ncdu \
    pulsemixer \
    sbctl \
    signal-desktop \
    steam \
    stow \
    syncthing \
    trash-cli \
    ttf-jetbrains-mono-nerd \
    udiskie \
    unarchiver \
    wl-clipboard \
    zathura zathura-pdf-poppler \
    dust \

paru -S \
    hyprpicker-git hyprlock-git hypridle-git \
    librewolf-bin \
    reflector \
    rivalcfg \
    tor-browser-bin \
    adw-gtk3-git \

paru --clean
