version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

#networks:
  #nginx-proxy-manager_default:
    #external: true

#add
#networks:
  #- nginx-proxy-manager_default

# For reverse proxy use: docker inspect CONTAINER ID to find IP
