version: '3.3'
services:
  portainer-ce:
    ports:
      - '9000:9000'
      - '8000:8000'
    container_name: portainer
    networks:
      - nginx-proxy-manager_default
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/root/docker/portainer:/data'
    image: 'portainer/portainer-ce:latest'

networks:
  nginx-proxy-manager_default:
    external: true
