#!/bin/sh

SHADER=/home/troy/.config/hypr/bluelight.glsl
CHECKSHADER=$(hyprctl getoption decoration:screen_shader -j | jq -r ".str")

if [[ $CHECKSHADER == $SHADER ]]; then
    hyprctl keyword decoration:screen_shader ""
    hyprctl notify -1 1000 "rgb(ff1ea3)" "Blue light filter is off"
else
    hyprctl keyword decoration:screen_shader $SHADER
    hyprctl notify -1 1000 "rgb(ff1ea3)" "Blue light filter is on"
fi
