version: "3"

services:
    client:
        image: nginx
        ports:
            - 8888:80
        volumes:
            - /home/docker/nginx:/usr/share/nginx/html
        networks:
          - nginxproxymanager_default
        restart: unless-stopped

networks:
  nginxproxymanager_default:
    external: true
