#!/bin/sh

device_amount=$(bluetoothctl devices | wc -l)

if [[ $device_amount = 1 ]]; then
	MAC=$(bluetoothctl devices | awk {'print $2'})
		[[ -z $MAC ]] && MAC=NoDeviceFound # Prevents accidental disconnect error
else
	select=$(bluetoothctl devices | awk {'print $3'} | bemenu --no-exec --fn "JetBrainsMono NF 10" -p "Bluetooth device:" )
	MAC=$(bluetoothctl devices | grep $select | awk {'print $2'}) 
		[[ -z $MAC ]] && MAC=NoDeviceFound # Prevents accidental disconnect error
fi

connect=$(bluetoothctl info $MAC | grep Connected: | awk '{print $2}')
if [[ $connect = no ]]; then 
	notify-send "Attempting to connect to $select"
	bluetoothctl connect $MAC || notify-send "Failed to Connect"
    pactl set-default-sink "bluez_output.$MAC.a2dp-sink"
elif [[ $connect = yes ]]; then
	notify-send "Attempting to disconnect $select"
	bluetoothctl disconnect $MAC 
fi
