#!/bin/sh

cat /etc/*-release | grep PRETTY_NAME | awk -F '=' '{print "os: " $2}'

uname -mr

pacman -Q | wc -l

uptime -p

cat /proc/cpuinfo | grep 'model name' | sort -u

lspci | grep ' VGA ' | cut -d" " -f 1 | xargs -i lspci -v -s {} | grep 'Subsystem:'

free -m

nodename=$(uname -n)
df -h /
if [[ $nodename == 'aorus' ]]; then
    df -h /mnt/wdhdd
fi
if [[ $nodename == 'x230' ]]; then
    cat /sys/class/power_supply/BAT0/capacity
    cat /sys/class/power_supply/BAT0/status
fi
