#!/bin/sh

cat /etc/*-release | grep PRETTY_NAME | awk -F '=' '{print "os: " $2}'

uname -mr

echo "packages: "

pacman -Q | wc -l

free -m
cat /proc/meminfo

lspci | grep ' VGA ' | cut -d" " -f 1 | xargs -i lspci -v -s {}

cat /proc/cpuinfo

df -h /
df -h /mnt/wdhdd

cat /proc/swaps

uptime -p
