#!/bin/sh

muteToggle = $(echo -e "Mute? (Y or N)")

if [[ $muteToggle == "Y" ]] || [[ $muteToggle == "y" ]]; then
    ffmpeg -i $1 -filter:v scale=1280:-1 -c copy -an $2
else;
    ffmpeg -i $1 -filter:v scale=1280:-1 -c:a copy $2


# ffmpeg -i skyscrapers.mp4 -c:v libvpx-vp9 -crf 40 -vf scale=1920:-2 -an output.webm
# <source src="videos/skyscrapers.webm" type="video/webm; codecs=vp9" />
